services:
  backend:
    container_name: bd2-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
      - ./core:/app/core
      - ./indexes:/app/indexes
      - ./parser:/app/parser
    environment:
      - FLASK_ENV=development

  frontend:
    container_name: bd2-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  bd2-data:
