FROM node:20-slim

WORKDIR /app/front/db-manager

# Copiar archivos de dependencias
COPY ./front/db-manager/package.json ./front/db-manager/package-lock.json ./

# Instalar dependencias
RUN npm ci || npm install

# Copiar el resto del código
COPY ./front/db-manager .

EXPOSE 5173

CMD ["npm", "run", "dev"]
