
FROM python:3.12-slim

WORKDIR /app

COPY . /app

# Instala dependencias
RUN pip install --no-cache-dir flask flask_cors lark

# Expón el puerto
EXPOSE 3001

# Define el directorio de trabajo del backend
WORKDIR /app/backend

CMD ["python", "app.py"]
